In [1]:
import pandas as pd

In [2]:
movies = pd.read_csv('http://bit.ly/imdbratings')

In [3]:
movies.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [4]:
movies.title.sort_values()

542                   (500) Days of Summer
5                             12 Angry Men
201                       12 Years a Slave
698                              127 Hours
110                  2001: A Space Odyssey
910                                   2046
596                               21 Grams
624                              25th Hour
708                       28 Days Later...
60                                3 Idiots
225                                 3-Iron
570                                    300
555                           3:10 to Yuma
427           4 Months, 3 Weeks and 2 Days
824                                     42
597                                  50/50
203                                  8 1/2
170                       A Beautiful Mind
941                       A Bridge Too Far
571                           A Bronx Tale
266                      A Christmas Story
86                      A Clockwork Orange
716                         A Few Good Men
750                    A Fish Called Wanda
276                   A Fistful of Dollars
612                     A Hard Day's Night
883                  A History of Violence
869              A Nightmare on Elm Street
865                        A Perfect World
426                              A Prophet
                      ...
207       What Ever Happened to Baby Jane?
562            What's Eating Gilbert Grape
719                When Harry Met Sally...
649                      Where Eagles Dare
33                                Whiplash
669                Who Framed Roger Rabbit
219        Who's Afraid of Virginia Woolf?
127                      Wild Strawberries
497    Willy Wonka & the Chocolate Factory
270                        Wings of Desire
483                           Withnail & I
920                                Witness
65             Witness for the Prosecution
970                            Wonder Boys
518                         Wreck-It Ralph
954                                  X-Men
248             X-Men: Days of Future Past
532                     X-Men: First Class
871                                     X2
695                      Y Tu Mama Tambien
403                             Ying xiong
235                                Yip Man
96                                 Yojimbo
280                     Young Frankenstein
535                                  Zelig
955                       Zero Dark Thirty
677                                 Zodiac
615                             Zombieland
526                                   Zulu
864                                  [Rec]
Name: title, Length: 979, dtype: object

OR

In [9]:
movies['title'].sort_values

<bound method Series.sort_values of 0                               The Shawshank Redemption
1                                          The Godfather
2                                 The Godfather: Part II
3                                        The Dark Knight
4                                           Pulp Fiction
5                                           12 Angry Men
6                         The Good, the Bad and the Ugly
7          The Lord of the Rings: The Return of the King
8                                       Schindler's List
9                                             Fight Club
10     The Lord of the Rings: The Fellowship of the Ring
11                                             Inception
12        Star Wars: Episode V - The Empire Strikes Back
13                                          Forrest Gump
14                 The Lord of the Rings: The Two Towers
15                                          Interstellar
16                       One Flew Over the Cuckoo's Nest
17                                         Seven Samurai
18                                            Goodfellas
19                                             Star Wars
20                                            The Matrix
21                                           City of God
22                                 It's a Wonderful Life
23                                    The Usual Suspects
24                                                 Se7en
25                                     Life Is Beautiful
26                          Once Upon a Time in the West
27                              The Silence of the Lambs
28                                Leon: The Professional
29                                           City Lights
                             ...
949                                           Home Alone
950                                                Bound
951                                        Sleepy Hollow
952                                         Pirate Radio
953                                The NeverEnding Story
954                                                X-Men
955                                     Zero Dark Thirty
956                             Manhattan Murder Mystery
957                          National Lampoon's Vacation
958                                   My Sister's Keeper
959                                 Deconstructing Harry
960                                     The Way Way Back
961                                               Capote
962                                   Driving Miss Daisy
963                                      La Femme Nikita
964                                              Lincoln
965                                            Limitless
966                                   The Simpsons Movie
967                                             The Rock
968                                  The English Patient
969                                  Law Abiding Citizen
970                                          Wonder Boys
971                                   Death at a Funeral
972                                       Blue Valentine
973                                The Cider House Rules
974                                              Tootsie
975                          Back to the Future Part III
976      Master and Commander: The Far Side of the World
977                                          Poltergeist
978                                          Wall Street
Name: title, Length: 979, dtype: object>

In [11]:
movies.sort_values('title', inplace=True)

In [12]:
movies.head()

,star_rating,title,content_rating,genre,duration,actors_list
542,7.8,(500) Days of Summer,PG-13,Comedy,95,"[u'Zooey Deschanel', u'Joseph Gordon-Levitt', ..."
5,8.9,12 Angry Men,NOT RATED,Drama,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."
201,8.1,12 Years a Slave,R,Biography,134,"[u'Chiwetel Ejiofor', u'Michael Kenneth Willia..."
698,7.6,127 Hours,R,Adventure,94,"[u'James Franco', u'Amber Tamblyn', u'Kate Mara']"
110,8.3,2001: A Space Odyssey,G,Mystery,160,"[u'Keir Dullea', u'Gary Lockwood', u'William S..."